### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by vitellolabs** [octavenz/wagtail-favicon#1]
Hello, 
I have been testing this package and it seems like it won't display favicon on any browser if `{{ root_url }}` is used in the templates. 
On the local dev server it evaluates to `localhost`. Upon removing that from the template the favicon displays correctly. 
Is there any reason to use `root_url` ? I see no use for it. Thanks!

**Comment by pjho** [comment]
Hey thanks for your comment. 

I think, from your description - if you go to `wagtailadmin > settings > sites` and ensure you have the hostname and port set the same as you are using on your dev server then you should see the icons working. Defaults are `localhost:80`. I just reinstalled from scratch and had to update to `localhost:8080` since that's the port my dev server is running on.

I think the main reason they are absolute urls is because open graph images require absolute urls - so I set these up that way as well. I'll do a bit of testing and see if I can just load these as relative and if so will remove the root_url part.
